### ISSUE TITLE
Additional images show

### ISSUE THREAD

**Issue by fdriver33** [PhocaCz/PhocaCartImageZoomPlugin#1]
If product has only one picture and no additional images, on product page is only one main image and not showing aby thumb of additional images. This is OK, but when I turn on ZOOM plugin, product page showing thumb additional images for main image only, even If product has no additional images.

**Comment by PhocaCz** [comment]
Hi,

try to test version 4.0.5:
https://github.com/PhocaCz/PhocaCartImageZoomPlugin/releases/download/4.0.5/plg_pcv_image_zoom_v4.0.5.zip

In parameters you can disable the displaying of main image as thumbnail in case there are no additional thumbnails


![img](https://i.imgur.com/C7sUcTa.png)

![img](https://i.imgur.com/vGLY1q1.png)

Let me know if this works for you.

**Comment by fdriver33** [comment]
Hi, 

thx for fast response. 
I didn`t see option in parameters, Probably my bad. 
I install 4.0.5 and disable option and everything work perfect. 

Thank you one more time :)

**Comment by PhocaCz** [comment]
>I didn`t see option in parameters, Probably my bad.

I added it now.

**Comment by fdriver33** [comment]
> I added it now.

You are super fast 👍
